//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "nanoFramework_Hardware_Esp32_DynamicIndication.h"

using hw_ctrl = Library_nanoFramework_Hardware_Esp32_DynamicIndication_nanoFramework_Hardware_Esp32_DynamicIndication_Controller;

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    hw_ctrl::NativeDispose___VOID,
    hw_ctrl::NativeInit___VOID__SZARRAY_I4__SZARRAY_I4__I4,
    hw_ctrl::NativeIsEnabled___BOOLEAN,
    hw_ctrl::NativeSetEnabled___VOID__BOOLEAN,
    hw_ctrl::NativeSetData___VOID__SZARRAY_U4,
    hw_ctrl::NativeSetUpdateInterval___VOID__U4,
    hw_ctrl::NativeGetUpdateInterval___U4,
    hw_ctrl::NativeTest1___BOOLEAN__SZARRAY_U4,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_Hardware_Esp32_DynamicIndication =
{
    "nanoFramework.Hardware.Esp32.DynamicIndication", 
    0x26D67B37,
    method_lookup,
    ////////////////////////////////////////////////////////////////////////////////////
    // check if the version bellow matches the one in AssemblyNativeVersion attribute //
    ////////////////////////////////////////////////////////////////////////////////////
    { 1, 0, 0, 0 }
};
