//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _NANOFRAMEWORK_HARDWARE_ESP32_DYNAMICINDICATION_H_
#define _NANOFRAMEWORK_HARDWARE_ESP32_DYNAMICINDICATION_H_

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
struct Library_nanoFramework_Hardware_Esp32_DynamicIndication_nanoFramework_Hardware_Esp32_DynamicIndication_Controller
{
    static const int FIELD_STATIC__DefaultUpdatePeriod_us = 0;

    NANOCLR_NATIVE_DECLARE(NativeDispose___VOID);
    NANOCLR_NATIVE_DECLARE(NativeInit___VOID__SZARRAY_I4__SZARRAY_I4__I4);
    NANOCLR_NATIVE_DECLARE(NativeIsEnabled___BOOLEAN);
    NANOCLR_NATIVE_DECLARE(NativeSetEnabled___VOID__BOOLEAN);
    NANOCLR_NATIVE_DECLARE(NativeSetData___VOID__SZARRAY_U4);
    NANOCLR_NATIVE_DECLARE(NativeSetUpdateInterval___VOID__U4);
    NANOCLR_NATIVE_DECLARE(NativeGetUpdateInterval___U4);
    NANOCLR_NATIVE_DECLARE(NativeTest1___BOOLEAN__SZARRAY_U4);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_Hardware_Esp32_DynamicIndication;

#endif  //_NANOFRAMEWORK_HARDWARE_ESP32_DYNAMICINDICATION_H_
